apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  replicas: 1 # Commencez par 1 pour l'installation
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
        # --- Container PHP-FPM ---
        - name: php
          image: joomla:php8.2-fpm
          env:
            - name: JOOMLA_DB_HOST
              value: mariadb-galera.default.svc.cluster.local
            - name: JOOMLA_DB_USER
              value: joomla
            - name: JOOMLA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: joomla-db-secrets
                  key: JOOMLA_DB_PASSWORD
            - name: JOOMLA_DB_NAME
              value: joomla
          volumeMounts:
            - name: joomla-storage
              mountPath: /var/www/html

        # --- Container Nginx ---
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: joomla-storage
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: joomla-storage
          persistentVolumeClaim:
            claimName: joomla-pvc
        - name: nginx-config
          configMap:
            name: joomla-nginx-config
---